server:
    port: 8081
    context-path: /uaa
security:
  oauth2:
    client:
      client-secret: acmesecret
      client-id: acme
      authorized-grant-types: authorization_code,refresh_token,password
      scope: write
    resource:
      user-info-uri: http://localhost:8081/uaa/user
  user:
    name: 'vale'
    password: 'pass'