server:
  port: 8081
  context-path: /uaa

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8081/uaa/oauth/token
      user-authorization-uri: http://localhost:8081/uaa/oauth/authorize
  user:
    name: 'vale'
    password: 'pass'